byhandpro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from byhand import views
from django.views.static import serve
from byhandpro import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
handler404 = 'longprofile.views.not_found'
handler500 = 'longprofile.views.server_error'


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('register/', views.register,name='register'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('',views.loginpage,name='login'),
    path('logoutuser',views.logoutuser,name='logoutuser'),
    path('accounts/',include('allauth.urls')),
    path('regcheck/',views.regcheck,name='regcheck'),


    #######
    path('check_email_exist/',views.check_email_exist,name='check_email_exist'),
    path('check_phone_exist/',views.check_phone_exist,name='check_phone_exist'),
    
    path('check_email_existe/',views.check_email_existe,name='check_email_existe'),
    path('check_phone_existe/',views.check_phone_existe,name='check_phone_existe'),
    #######

    path('register_as/',views.register_as,name='register_as'),
    path('register_company/',views.register_company,name='register_company'),
    path('register_freelancer/',views.register_freelancer,name='register_freelancer'),
    path('register_professional/',views.register_professional,name='register_professional'),
    path('register_public/',views.register_public,name='register_public'),
    path('register_student/',views.register_student,name='register_student'),
    path('register_enterprenur/',views.register_enterprenur,name='register_enterprenur'),
    ###########
    path('userslist/',views.userslist,name='userslist'),
    path('userview/<int:id>/',views.userview,name='userview'),
    path('follow/<int:id>/',views.follow,name='follow'),
    path('unfollow/<int:id>/',views.unfollow,name='unfollow'),

    ##############settings#################
    path('change_password_internal/',views.passwordchange_internal,name = 'change_password_internal'),
    path('edit_profile/',views.edit_profile,name = 'edit_profile'),
    path('changeprofile/',views.changeprofile,name = 'changeprofile'),
    path('change_password/',views.change_password,name ='change_password'),
    
    
    ###################forgot password#####################
    # path('resetpassword/',views.resetpassword,name ='resetpassword'),
    # path('reset_password/',
    #     auth_views.PasswordResetView.as_view(template_name="passwordchange/password_reset.html"),
    #     name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="passwordchange/password_reset_sent.html"),
         name="password_reset_done"),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name="passwordchange/password_reset_form.html"),
    #      name="password_reset_confirm"),
    
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="passwordchange/password_reset_done.html"),
         name="password_reset_complete"),
    
    
    path('reset_passwordc/',views.reset_password,name ="reset_passwordc"),
    
    path('reseta/<uidb64>/<token>/',views.reseta, name='reseta'),    

    #############Settings ##############

    #####
    path('social/',include("social.urls")),

    ###################settings########################
    path('editprofile/',views.editprofile,name="editprofile"),
    #################notification#########################

    path('notification/',views.showNotification,name="notification"),
    path('certificate_notification/',views.certificate_notification,name="certificate_notification"),

    path('longprofile/',include("longprofile.urls")),
    path('chat/',include("chat.urls")),
    path('activity/',include("activity.urls")),

    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from chat import views

urlpatterns = [
    path("chatroom/<int:pk>", views.chatroom, name = "chatroom"),
    path("ajax/<int:pk>/", views.ajax_load_messages, name="chatroom-ajax"),
    path("messageDelete/", views.messageDelete, name="messageDelete"),
    # path("switchUser/", views.switchUser, name="switchUser"),
    path("createGroup/", views.createGroup, name="createGroup"),
    path("groupchatroom/<int:pk>/", views.groupchatroom, name = "groupchatroom"),
    path("groupchatroom_base/", views.groupchatroom_base, name = "groupchatroom_base"),
    path("ajax_load_messages_group/<int:pk>/", views.ajax_load_messages_group, name="ajax_load_messages_group"),
    path("messageDelete_group/", views.messageDelete_group, name="messageDelete_group"),
    path("updateGroupinfo/<int:pk>/", views.updateGroupinfo, name="updateGroupinfo"),
    path("updateGroupMembers/<int:pk>/", views.updateGroupMembers, name="updateGroupMembers"),
    path("exitgroup/<int:pk>/", views.exitgroup, name="exitgroup"),
    path("chatroom_base/", views.chatroom_base, name="chatroom_base"),
    path("chatcount/", views.chatcount, name="chatcount"),
]

longprofile/urls.py
from django.conf.urls import url
from django.urls import path
from longprofile import views

urlpatterns = [
    path('home/',views.home,name="home"),
    path('cards/',views.cards,name="cards"),
    path('company_card_update/',views.company_card_update,name="company_card_update"),
    path('personal_card_update/',views.personal_card_update,name="personal_card_update"),
    url('^personalcardDelete/(?P<pk>\d+)/$',views.personalcardDelete,name="personalcardDelete"),
    url('^personalcardview/(?P<slug>[-\w]+)-(?P<pk>\d+)/$',views.personalcardview,name="personalcardview"),
    url('^personalcardviewpdf/(?P<pk>\d+)/$',views.personalcardviewpdf,name="personalcardviewpdf"),
    path('autosuggest', views.autosuggest, name='autosuggest'),
    path('manualsearch', views.manualsearch, name='manualsearch'),
    url(r'^searchprofile_full_view/(?P<pk>\d+)/$',views.searchprofile_full_view,name="searchprofile_full_view"),
    path('profile_full_view/',views.profile_full_view,name="profile_full_view"),
    path('home2/',views.home2,name="home2"),
    path('starRating/',views.starRating,name="starRating"),
    # path('follow/<str:username>',views.follow,name="follow"),
    url('^follow/(?P<pk>\d+)/$',views.follow,name="follow"),
    url('^countAndNotifications/(?P<pk>\d+)/$',views.countAndNotifications,name="countAndNotifications"),
    url('^endorse/(?P<pk>\d+)/$',views.endorse,name="endorse"),
    url('^connection/(?P<pk>\d+)/$',views.connection,name="connection"),
    url('^connectionList/(?P<pk>\d+)/$',views.connectionList,name="connectionList"),
    url('^connectionDelete/(?P<pk>\d+)/$',views.connectionDelete,name="connectionDelete"),
    url('^connectionAccept/(?P<pk>\d+)/$',views.connectionAccept,name="connectionAccept"),
    #event
    path('createevent/',views.createevent,name="createevent"),
    url('^eventOtheruser/(?P<pk>\d+)/$',views.eventOtheruser,name="eventOtheruser"),
    url('^eventSave/(?P<pk>\d+)/$',views.eventSave,name="eventSave"),
    url('^deleteevent/(?P<pk>\d+)/$',views.deleteevent,name="deleteevent"),
    #enquiry
    url('^createEnquiry/(?P<pk>\d+)/$',views.createEnquiry,name="createEnquiry"),
    url('^myenquiry/',views.myenquiry,name="myenquiry"),
    url('^enquirySave/(?P<pk>\d+)/$',views.enquirySave,name="enquirySave"),
    url('^deleteenquiry/(?P<pk>\d+)/$',views.deleteenquiry,name="deleteenquiry"),
    #appoinment
    url('^createAppoinment/(?P<pk>\d+)/$',views.createAppoinment,name="createAppoinment"),
    url('^myappoinment/',views.myappoinment,name="myappoinment"),
    url('^approveappointment/(?P<pk>\d+)/$',views.approveappointment,name="approveappointment"),
    url('^updateappointment/(?P<id>\d+)/$',views.updateappointment,name="updateappointment"),
    url('^deleteappointment/(?P<pk>\d+)/$',views.deleteappointment,name="deleteappointment"),
    #delete
    url('^expertisedelete/(?P<pk>\d+)/$',views.expertisedelete,name="expertisedelete"),
    url('^experiencedelete/(?P<pk>\d+)/$',views.experiencedelete,name="experiencedelete"),
    url('^projectsdelete/(?P<pk>\d+)/$',views.projectsdelete,name="projectsdelete"),
    url('^achievementsdelete/(?P<pk>\d+)/$',views.achievementsdelete,name="achievementsdelete"),
    url('^certificationdelete/(?P<pk>\d+)/$',views.certificationdelete,name="certificationdelete"),
    url('^clientdelete/(?P<pk>\d+)/$',views.clientdelete,name="clientdelete"),
    url('^testimonialdelete/(?P<pk>\d+)/$',views.testimonialdelete,name="testimonialdelete"),
    #about
    path('aboutupdate/',views.aboutupdate,name="aboutupdate"),
]

byhand/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

# from byhandpro.social.models import Post


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, username, first_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, username, first_name, password, **other_fields)

    def create_user(self, email, username, first_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username,
                          first_name=first_name, **other_fields)
        user.set_password(password)
        user.save()
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True,null=True)
    username = models.CharField(max_length=100,unique=False, null=True,blank = True)
    phone = models.CharField(max_length=12,default="")
    first_name = models.CharField(max_length=150, blank=True,null = True)
    last_name = models.CharField(max_length=150, blank=True,null = True)
    start_date = models.DateTimeField(default=timezone.now)
    # about = models.TextField(_(
    #     'about'), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name']

    def __str__(self):
        return self.username

class UserExtend(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    company_name = models.CharField(max_length=100,null=True)
    created_by = models.CharField(max_length=100,null=True)
    position = models.CharField(max_length=100,null=True)
    profession = models.CharField(max_length=100,null=True)
    institution_name = models.CharField(max_length=100,null=True)
    degree = models.CharField(max_length=100,null=True)
    specilisation = models.CharField(max_length=100,null=True)
    start_year = models.CharField(max_length=100,null=True)
    end_year = models.CharField(max_length=100,null=True)
    group = models.CharField(max_length = 100,null = True)

class Follow(models.Model):
    following = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True, related_name="who_follows")
    follower = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True,related_name="who_following")
    follow_time = models.DateTimeField(auto_now=True)


class Bio(models.Model):
    GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
        ('3', 'Transgenders'),
        ('4', 'Not To Say')
    )
    user = models.OneToOneField(CustomUser,on_delete = models.CASCADE, blank = True,null = True)
    address = models.CharField(max_length = 500,null = True)
    website = models.CharField(max_length = 50 , null = True)
    image = models.ImageField(upload_to='media',null=True)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES, null=True)
    
    
    def profile_pic(self):
        try:
            url = self.image.url
        except:
            url = "/static/img/unknown.jpg"
        return url

    def __unicode__(self):
        return self.user









# class Post(models.Model):
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,blank=True, null=True)
#     caption = models.CharField(max_length=500,null=True)
#     like = models.IntegerField(null=True)
#     date = models.DateTimeField(auto_now=True)
#     image = models.ImageField(upload_to='media',null=True)

# class Stream(models.Model):
#     following = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True, related_name='stream_following')
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
#     date = models.DateTimeField()

longprofile/forms.py
from django import forms
from longprofile.models import *


# class Company_cardForm(forms.ModelForm):
#     class Meta:
#         model = Company_card
#         fields = ('name','email','job','company_name','address1','address2','address3','phone1','phone2','logo')
# class Personal_cardForm(forms.ModelForm):
#     class Meta:
#         model = Personal_card
#         fields = ('name','email','job','company_name','address1','address2','address3','phone1','phone2','logo','photo')
class CreateEventForm(forms.ModelForm):
    class Meta:
        model = CreateEvent
        fields = ('name','description','image')
class CreateEnquiryForm(forms.ModelForm):
    class Meta:
        model = CreateEnquiry
        fields = ('title','description')
class CreateAppoinmentForm(forms.ModelForm):
    class Meta:
        model = CreateAppoinment
        fields = ('name','purpose','description','date','time')

templates/longprofile/emptysearch.html
{% extends 'longprofile/base.html' %}
{% block content %}
{% load static %}
    <h4 style="padding: 10% 0% 0% 23%; color:red;">We couldn't find a match for {{search}}</h4>
{% endblock %}

templates/longprofile/event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <h2>Event</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    <h2>MY event</h2>
    {% for i in my_event %}
        <p>Event name:{{i.name}}</p>
        <p>auther:{{i.user.first_name}}</p>
        <p>{{i.description}}</p>
        ----------------------------------------------
    {% endfor %}
    <h2>Saved Event</h2>
    {% for i in savedEventView %}
        <p>Name:{{i.event.name}}</p>
        <p>Author:{{i.event.user.first_name}}</p>
        <p>{{i.event.description}}</p>
        <a href="{% url 'deleteevent' i.pk %}" id = "savebtn{{i.id}}"><i id="saveicon{{i.id}}" class="fa fa-star text-warning"  style="font-size: 30px;"></i></a><br>
    {% endfor %}
</body>
</html>

templates/longprofile/eventOtheruser.html
{% extends 'longprofile/base.html' %}
{% block content %}
{% load static %}
<div class="container-fluid">
    <div class="row m-0">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xm-12 center-scroll row-height pt-3">
            <div class="row m-0">
                <div class="post-heading w-100">
                <img src="{% static 'img/Group 3572.png' %}" alt="" style="width: 30px;" > <span class="px-4 items">Activities</span>
            </div>
            <div class="mt-3 p-0 border-bottom text-center">
              
                <div class="text-center d-inline-block post post-event" data-toggle="modal" data-target="#createEvent-modal"> 
                  <button class="btn btn btn-default btn-rounded verification-btn border-blue"><i class="fa fa-calendar-day"></i></button>
                  <p>Event</p>
                </div>
                
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xm-12 mt-3">
                <h4 class="text-primary">Event</h4>
                {% for i in my_event %}
                    <div class="card mt-4 p-0 border" style="border-radius:25px;">
                        <div class="card-header border-0">
                            <div class="card-title">
                                {% for j in i.user.bio_set.all %}
                                <div class="d-flex"> <img src="{{j.image.url}}" class="rounded-circle " height="70" alt="" loading="lazy"/>
                                {% empty %}
                                <div class="d-flex"> <img src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg" class="rounded-circle " height="70" alt="" loading="lazy"/>
                                
                                {% endfor %}
                                    <div class="m-2 eventpost-details">
                                        <h6 class=""><strong>{{i.name}}</strong></h6>
                                        <p>{{i.user.first_name}}</p>
                                    </div>
                                </div>
                                <div>
                                    <button type="button" class="custom-btn" title="Save"><i class="far fa-bookmark"></i></button>
                                    <small class="text-muted">Posted 3 mins ago</small> </div>
                                </div>
                            </div>
                            <div class="card-body event-body d-flex">
                                <img src="{{i.image.url}}" class="card-img-bottom mr-3" style="width:50%;" alt="..."/>
                                    <div class="">
                                        <p class="card-text text-info">  <span class="font-weight-bold">Name Surname</span>{{i.description}}</p>
                                        {% if i in saved_event %}
                                        <a href="{% url 'eventSave' i.pk %}" id = "savebtn{{i.id}}"><i id="saveicon{{i.id}}" class="fa fa-star text-warning" style="font-size: 1.5rem;"></i></a>
                                        {% else %}
                                        <a href="{% url 'eventSave' i.pk %}" id = "savebtn{{i.id}}"><i id="saveicon{{i.id}}" class="fa fa-star" style="font-size: 1.5rem;"></i></a>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="card-footer border-0">
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                        $("#savebtn{{i.id}}").click(function(e){
                            e.preventDefault();
                            var href = this.href;
                            $.ajax({
                                url : href,
                                success : function(response){
                                    console.log(response.is_save)
                                    if(response.is_save === true){
                                        $("#saveicon" + response.save_id).removeClass('fa fa-star-o text-warning');
                                        $("#saveicon" + response.save_id).attr('class', 'fa fa-star text-warning');
                                        
                                        // $("#star").attr('class', 'fa fa-star text-warning');
                                    }
                                    else{
                                        $("#saveicon" + response.save_id).removeClass('fa fa-star text-warning');
                                        $("#saveicon" + response.save_id).attr('class', 'fa fa-star-o text-warning');
                                        
                                        // $("#star").attr('class', 'fa fa-star-o text-warning');
                                    }
                                }
                            })
                        })
                    </script>
                {% endfor %}
          </div>
    </div>
</div>
      <!-- /#Sidebar -->
      <script>
        function myFunction(){
            var x = document.getElementById("sidebar-wrapper");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else{
                x.style.display = "none";
            }
        }
</script>
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    {% for i in my_event %}
        <p>Event name:{{i.name}}</p>
        <p>author:{{i.user.first_name}}</p>
        <p>{{i.description}}</p>
        {% if i in saved_event %}
        <a href="{% url 'eventSave' i.pk %}" id = "savebtn{{i.id}}"><i id="saveicon{{i.id}}" class="fa fa-star text-warning"  style="font-size: 30px;"></i></a><br>
        {% else %}
        <a href="{% url 'eventSave' i.pk %}" id = "savebtn{{i.id}}"><i id="saveicon{{i.id}}" class="fa fa-star-o text-warning"  style="font-size: 30px;"></i></a><br>
        {% endif %}
        ----------------------------------------------
        <script>
            $("#savebtn{{i.id}}").click(function(e){
                e.preventDefault();
                var href = this.href;
                $.ajax({
                    url : href,
                    success : function(response){
                        console.log(response.is_save)
                        if(response.is_save === true){
                            $("#saveicon" + response.save_id).removeClass('fa fa-star-o text-warning');
                            $("#saveicon" + response.save_id).attr('class', 'fa fa-star text-warning');
                            
                            // $("#star").attr('class', 'fa fa-star text-warning');
                        }
                        else{
                            $("#saveicon" + response.save_id).removeClass('fa fa-star text-warning');
                            $("#saveicon" + response.save_id).attr('class', 'fa fa-star-o text-warning');
                            
                            // $("#star").attr('class', 'fa fa-star-o text-warning');
                        }
                    }
                })
            })
        </script>
    {% endfor %}
</body>
</html> -->

templates/longprofile/home2.html
{% extends 'longprofile/base.html' %}
{% load static %}
{% block content %}

<h2>home page 2..</h2>

{% endblock %}

templates/longprofile/myappoinment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <h2>My Appointment</h2>
        <h4>Pending</h4>
        {% for i in pending %}
            <p>Name:{{i.name}}</p>
            <p>Purpose of visit:{{i.purpose}}</p>
            <p>{{i.description}}</p>
            <p>Date:{{i.dateandtime}}</p>
            <a type="button" class="btn btn-success" id="approve" role="button" href="{% url 'approveappointment' i.pk %}">Approve</a>
            <a type="button" class="btn btn-primary " id="modify" role="button" href="{% url 'updateappointment' i.pk %}">Modify</a>
            <a type="button" class="btn btn-danger" id="delete" role="button" href="{% url 'deleteappointment' i.pk %}">Delete</a><br>
            -----------------------------------------------
        {% endfor %}
    </div>
    <h4>Active</h4>
    {% for i in actived %}
        <p>Name:{{i.name}}</p>
        <p>Purpose of visit:{{i.purpose}}</p>
        <p>{{i.description}}</p>
        <p>Date:{{i.dateandtime}}</p>
        <a type="button" class="btn btn-danger" id="delete" role="button" href="{% url 'deleteappointment' i.pk %}">Delete</a><br>
    {% endfor %}
    <h4>Complete</h4>
    {% for i in complete %}
        <p>Name:{{i.name}}</p>
        <p>Purpose of visit:{{i.purpose}}</p>
        <p>{{i.description}}</p>
        <p>Date:{{i.dateandtime}}</p>
        <a type="button" class="btn btn-danger" id="delete" role="button" href="{% url 'deleteappointment' i.pk %}">Delete</a><br>
    {% endfor %}
    <h2>Requested Appointment</h2>
    {% for i in requested %}
        <p>Recevier:{{i.enquired_person.first_name}}</p>
        <p>Purpose of visit:{{i.purpose}}</p>
        <p>{{i.description}}</p>
        <p>Date:{{i.dateandtime}}</p>
    {% endfor %}
</body>
</html>

templates/longprofile/personal_card_update.html
<html>
    <body>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="uploadimg">Upload front</label>
            <input type="file" id="uploadimg" name="uploadimg" value="{{view.front_img}}"><br><br>
            <label for="name">Name</label>
            <input type="text" id="name" name="name" value="{{view.name}}"><br><br>
            <label for="service">service</label>
            <input type="text" name="service" id="service" value="{{view.services}}"><br><br>
            <label for="mobile">Mobile no</label>
            <input type="number" name="mobile" id="mobile" value="{{view.mobile}}"><br><br>
            <label for="whatsup">whatsup no</label>
            <input type="number" name="whatsup" id="whatsup" value="{{view.whatsup}}"><br><br>
            <label for="cmp_name">Complany name</label>
            <input type="text" name="cmp_name" id="cmp_name" value="{{view.company_name}}"><br><br>
            <label for="Website">Website</label>
            <input type="text" name="Website" id="Website" value="{{view.website}}"><br><br>
            <label for="email">email</label>
            <input type="text" name="email" id="email" value="{{view.email}}"><br><br>
            <label for="location">location</label>
            <input type="text" name="location" id="location" value="{{view.location}}"><br><br>
            <label for="cmplocation">Company location</label>
            <input type="text" name="cmplocation" id="cmplocation" value="{{view.company_location}}"><br><br>
            <label for="uploadback">Upload back</label>
            <input type="file" id="uploadback" name="uploadback" value="{{view.back_img}}"><br><br>
            <label for="detail">Other Details</label>
            <input type="text" name="detail" id="detail" value="{{view.details}}"><br><br>
            <input type="submit">
        </form>
    </body>
</html>

templates/longprofile/profile_full_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Personal view</h2>
    <div>
        <a href="#" style="padding-right: 15px;">Post</a>
        <a href="{% url 'event' %}" style="padding-right: 15px;">Event</a>
        <a href="{% url 'myenquiry' %}" style="padding-right: 15px;">Enquiry</a>
        <a href="{% url 'myappoinment' %}">Appoinment</a>
    </div>
</body>
</html>